### ISSUE TITLE
LUA can now read and write files

### ISSUE THREAD

**Issue by SubhadeepJasu** [yumiris/HXE#12]
Kirby developed a custom chimera utility which removes most of the restrictions. According to him it is possible to read and write files with it. So, hopofully the post processing system will be using normal files stored else where instead of initc. We can also do that for all of them. @yumiris What do you say?

**Comment by SubhadeepJasu** [comment]
Ignore what I said before. The launcher will be made the way you are making it now. LUA will only supplement the limitations of HSC. I'll just need the location where the launcher stores its settings. So there is a cross connection between the loader and LUA. UX is the priority now. Don't stop doing whatever you are doing.

**Comment by MirisWisdom** [comment]
@SubhadeepJasu 

Hmm, wasn't Chimera's lack of I/O a security precaution? In this case, though, we'd be reading data rather than scripts, so I think we should be safe.

Can files be read from directories outside of SPV3? Because if that's possible, then we will no longer ever have to deal with admin rights problems.

**Comment by SubhadeepJasu** [comment]
Just wanted to know how would you want it. We got some possibilities here.

**Comment by MirisWisdom** [comment]
Ah, I see.

The loader currently doesn't store any of its _own_ settings like it used to. OpenSauce settings are stored directly inside the OpenSauce XML. The same applies for Chimera and HCE/SPV3 stuff, e.g. video settings are stored in `blam.sav`, and post-processing in `initc.txt`, and Chimera in `chimera.bin`.

Only unique settings the loader has is the overrides file, which is located in `%APPDATA%\SPV3\overrides.xml`

However, if it will store its own settings (e.g. loading in window mode, Sapien executable path), it would be located in `%APPDATA%\SPV3\configuration.xml`

**Comment by SubhadeepJasu** [comment]
hmm. Honestly how much functionality would you like to be handled by LUA?

**Comment by MirisWisdom** [comment]
Depends on the functionality in question. What functionality could be handled by Lua?

---

~~Just saw your email about the floats. Blah, it never crossed my mind that all f variables are floats.~~

~~I have an idea. Pass this onto Kirby:~~

~~Let's say F1 is out of bounds. We can divide F1 by F2, and store the new result in F1. Of course, we would store F2 as well to use it for multiplication later on.~~

~~This leaves us with two variables with smaller values, rather than one variable with an enormous value. When we need to get back the original value, we can simply multiply F1 by F2, and then decode it like we usually do.~~

```
f1 = 32768
f2 = 8

f1 = f1 / f2
   = 4096

---

f1 = f1 * f2
   = 32768
```

That won't solve the out of bounds index when getting the variable back. Oops!

**Comment by SubhadeepJasu** [comment]
> @Kirby_422
@Masterz1337
We need to classify what data is handled by launcher and what is by LUA
honestly using LUA and using launcher is the same thing technically
both will be stripped if SPV3 has to be in MCC
Right now
So the priority must be user experience
Somethings are better off in the launcher
like video settings
developer mode
console mode
eax
screenshot mode
cinematic bars
gamepads
While ...
stuff like
resume
opensauce settings
pp settings
can be handled by LUA
it actually solves a lot of our previous problems
regarding windows security and user account access
We really need to sit this out
We also need to be very much resourceful
any resource we save in HSC can be used for something better to happen
or solve an existing issue

**Comment by SubhadeepJasu** [comment]
Now that is what I wrote to them. They haven't yet replied.

**Comment by MirisWisdom** [comment]
Well, can Lua read a file from the user's documents folder? If it can, then the loader can write the initc.txt there, and Lua can read it from there. That'll prevent the UAC from barking whenever the loader writes in Program Files.

**Comment by SubhadeepJasu** [comment]
> I leave it all to you and Yumi
Whatever you think is best
I just need to know how we will hook all this into the maps, so that we can add new skulls/features into the UI and LUA postlaunch so we can add new skulls/scoring without having to recompile maps
sbdJazzToday at 12:04 AM
Anything that comes after launch can be placed in launcher
Any other feature which is there during release is pretty much defnitive at that point
Masterz1337Today at 12:05 AM
I imagine post launch we will update LUA, UI and lancher to add more skulls and features
other than firefight
sbdJazzToday at 12:05 AM
well we will be recompiling anyway
it only adds stuff on my end to some degree
so
i'll add place holder tags for future releases
